export const keyValue = {
  //Weekly Subcategory table
  sub_cat_nm: '항목',
  stock_qty: '재고',
  week_ratio: '매출비중',
  week_growth: '전년비',
  woi: '재고주수',
  sale_rate: '판매율',
  week_sale_qty_cy: '판매량',
  end_date: '날짜',
  sales_kor_cy: '위탁총판매',
  sales_kor_retail_cy: '국내',
  sales_dutyrfwhole_cy: '면세RF도매',
  sales_chn_cy: '중국',
  sales_gvl_cy: '홍마대',
  domain1_nm: '항목',
  prdt_nm: '제품명',
  style_cd: '제품코드',
  cls: '항목',
  ratio: '비중',
  qty_cy: '판매량 (당해)',
  qty_py: '판매량 (전년)',
  growth: '전년비',
  url: '제품이미지',
};
